version: "3.7"

services:
  web:
    container_name: django_nginx
    build: 
      context: .
      dockerfile: Dockerfile

    networks: 
      test_net:
        ipv4_address: 172.29.1.1
  
    command:
      # sleep infinity
      # python manage.py runserver
      #  0.0.0.0:8000
      gunicorn hello_django.wsgi:application --bind 0.0.0.0:8000

    volumes:
      - ./app:/djangonginx

    # ports:
      # - 8000:8000
    expose:
      - 8000


    env_file: 
      # - ./.env.dev
      - ./.env.prod

    depends_on:
      - db

  db:
    container_name: postgres_db
    image: postgres:12-alpine
    
    # restart: unless-stopped
    
    # ports:
    #   - 5432:5432

    networks: 
      test_net:
        ipv4_address: 172.29.1.2

    volumes:
      - postgres-data:/var/lib/postgresql/data

    env_file: 
      - ./.env.prod.db
    
      # there are in env.prod.db
    # environment: 
    #   - POSTGRES_DB=hello_django_dev
    #   - POSTGRES_USER=hello_django
    #   - POSTGRES_PASSWORD=supersecretpassword

    
  nginx:
    build: ./nginx
    ports: 
      - 1337:80
    networks: 
      test_net:
        ipv4_address: 172.29.1.3
    depends_on: 
      - web

volumes:
  postgres-data:

networks: 
  test_net:
    ipam: 
      driver: default
      config: 
        - subnet: 172.29.1.0/16

